#!/bin/bash -l

export PATH=/usr/local/bin:$PATH

# Cleanup
find /var/salesforce-fetcher/ -name output.csv -mtime +1 -exec rm {} \;

# Import from salesforce
/usr/local/bin/salesforce-fetcher --config-file /etc/salesforce-fetcher/settings.yml

# Load into Vertica
/usr/local/bin/vertica-csv-loader /usr/local/virtualenvs/vertica-csv-loader/vertica_loader/configs/salesforce-loads.yaml
