#!/bin/bash

. /etc/nubis-config/boomi.sh

/usr/local/virtualenvs/boomi/bin/python -m mozilla_etl.boomi.workday.employees "$Workday_Engine" --local

mkdir -p /tmp/etl/brickftp/etl/centerstone/downloads /tmp/etl/centerstone

sftp files.manhattan-online.com:/mozilla/prod/ << EOF
put /tmp/etl/centerstone/Mozilla_Active_Users.txt
put /tmp/etl/centerstone/Mozilla_Termed_Users.txt
put /tmp/etl/centerstone/workday-users.csv
EOF

sftp mozilla.brickftp.com:etl/centerstone/downloads <<EOF
put /tmp/etl/centerstone/Mozilla_Active_Users.txt
put /tmp/etl/centerstone/Mozilla_Termed_Users.txt
put /tmp/etl/centerstone/workday-users.csv
EOF
