#!/bin/bash -l

# Run a cronjob, and record start/end/status to prometheus metrics
# usage:
#  nubis-cron name-of-cron-job "commands to execute"

cleanup () {
 rm -f "$METRICS" 2>/dev/null
}
trap cleanup EXIT

METRICS=$(mktemp)

METRICS_PATH=/var/lib/node_exporter/metrics
LOGS_PATH=/var/log/nubis-cron

JOB=$1
shift

START=$(date +%s)

# If not invoked via a terminal, redirect stdout/stderr to log file
if [ ! -t 0 ]; then
  LOG_FILE="$LOGS_PATH/$JOB.log"
  exec &> >( ts >> "$LOG_FILE") 2>&1
  echo "Cron starting: $START"
fi

bash -c "$*"

RV=$?

END=$(date +%s)
DURATION=$(( END - START ))

cat <<EOF > "$METRICS"
# HELP nubis_cron_end Metric created by nubis-cron
nubis_cron_end{cronjob="$JOB"} $END
# HELP nubis_cron_start Metric created by nubis-cron
nubis_cron_start{cronjob="$JOB"} $START
# HELP nubis_cron_duration Metric created by nubis-cron
nubis_cron_duration{cronjob="$JOB"} $DURATION
# HELP nubis_cron_status Metric created by nubis-cron
nubis_cron_status{cronjob="$JOB"} $RV
EOF

mv -f "$METRICS" "$METRICS_PATH/nubis_cron_$JOB.prom"

if [ ! -t 0 ]; then
  echo "Cron Duration: $DURATION"
  echo "Cron Exit Status: $RV"
fi

# Propagate exit code
exit $RV
